### ISSUE TITLE
Login error when using enex2paperless tool

### ISSUE THREAD

**Issue by gianniginom** [kevinzehnder/enex2paperless#3]
I am experiencing an issue when trying to login to my Paperless instance using the enex2paperless tool. Direct API calls to Paperless work correctly using the same credentials, so the problem seems isolated to how enex2paperless is handling authentication. 

When running enex2paperless, I receive an error message even though the username and password in the config.yaml match my Paperless credentials. The tool is currently marked as alpha so bugs are expected. Please let me know if any logs or additional troubleshooting steps could help identify the root cause of this login error. Thank you for developing enex2paperless - 

I look forward to using it once this authentication problem is resolved.

**Comment by kevinzehnder** [comment]
Interesting. Yea there seems to be something wrong about the config and/or authentication mechanism. I didn't run into any such problems personally, but I'll investigate this. Others have had similar problems with this as well. Thanks for the feedback.

**Comment by wiedsche** [comment]
I had similar issues when using the recent version of the tool. Paperless declined authentication.
I found out, that the username configures in the `config.yaml` was not used when authenticating. Instead the username of my windows user was taken. 
Therefore I changed my account name in paperless to the username of my windows setup and then it worked.

**Comment by gianniginom** [comment]
Hi,

Actually I noticed the same thing and changing the username it works. So I compiled for Macos and it works with the identifiers.

**Comment by kevinzehnder** [comment]
@wiedsche is correct. In Windows the username from the config.yaml does not get picked up. I hadn't tested that as I ran it on linux where this problem doesn't exist. Apparently it's also working correctly in MacOS according to @gianniginom. So I think it should be an easy fix, let's see.

**Comment by kevinzehnder** [comment]
I've released 0.0.4, try that and see how it goes. I've also added a `-v` flag for debug logs.
