### ISSUE TITLE
Other Fileformats

### ISSUE THREAD

**Issue by giukanis** [kevinzehnder/enex2paperless#4]
Hi, 
not a bug, but a feature request.
Since I have a lot of Office files (Excel, Word and Powerpoint) and Pictures (JPG and PNG) in my evernote notebooks it would be nice to import them also.
Perhaps it would be possible to use a command line parameter to specify which fileformats should be imported.

What do you think? Would this be possible?

Cheers,
Lars.

**Comment by kevinzehnder** [comment]
Hey,
Thanks for the suggestion.. I think that should be doable, I'll see what I can do.

**Comment by kevinzehnder** [comment]
I've release v0.0.5 now, which handles multiple file types. Let me know if something isn't working.

**Comment by giukanis** [comment]
Hi, thanks a lot. It is working fine. 
Just two points:
1. is it possible to also have xlsx, docx and pptx support?
2. for images it would be nice to have a parameter for lowest resolution so that too small images (like in mail-footers) will be not imported
Cheers,
Lars

**Comment by kevinzehnder** [comment]
I didnt have time to include all the specific filetypes individually, but you can add "any" as filetype and all types will get processed. See the updated README. 
Good suggestion for the images, I might try that.
