### ISSUE TITLE
Multiple pdf files in one note fails

### ISSUE THREAD

**Issue by wiedsche** [kevinzehnder/enex2paperless#5]
I'm note sure, but it seems, that if there are multiple PDF files in a single note, the import will only handle only the first first file correctly. The other files will generate a weird error message in paperless-ngx, saying that the document could not be read. Uploading these pdf files manually works perfectly.

**Comment by kevinzehnder** [comment]
I couldn't replicate this problem in my tests. I was able to correctly import 2 PDFs from a single note. 

Can you show me the paperless logs?
