### ISSUE TITLE
Tags do not get imported

### ISSUE THREAD

**Issue by gunters63** [kevinzehnder/enex2paperless#6]
I always searched for an alternative to Evernote.

Now I found paperless-ngx and your nifty tool :)

It was working great on the first try, except one thing. I made heavy use of tags in Evernote, but no tags were imported to paperless.

What can I do to troubleshoot this?

Ah, one more thing: In a Enex-File it is no problem to have several notes with the same title. I have some notes in my Evernote with the same title (like tax declaration.pdf) where I never bothered to change the title because I always could look on the ocr'd content or the creation date. Would it be possible to rename such notes automatically (just append a running number like -1, -2 etc.).

**Comment by kevinzehnder** [comment]
try running with -v flag for more verbose logs. The tool should try to create the tags it found in the notes and the logs have entries about the tag creation. I'll see if I can create an even more verbose version to pin down errors like these. Also, check the paperless logs for infos. 

About your second point: the original filenames get imported too, so maybe that helps trying to organize everything?

**Comment by kevinzehnder** [comment]
Do you have special characters or spaces in your tags? Maybe they arent compatible and need to be converted somehow. I dont validate tag names at all.

**Comment by gunters63** [comment]
I ran the import with -v and i didn't see any messages about tag creation.
I also think I don't have any special characters in the tags.

Tomorrow I will make some tests, creating a new notebook in Evernote with just one note with some tags and export the notebook as Enex and try to import it. I will try the legacy Evernote for Windows and the new (Electron) version and post the results and the logs here.

**Comment by gunters63** [comment]
ok I made one Notebook with Evernote 10.81 for windows now:

![image](https://github.com/kevinzehnder/enex2paperless/assets/90346/8ac81acf-cfb6-4d70-ac11-3f5237d3d0a3)

Just one note with one tag (tag1).

Here the log:

```
C:\Users\gunte\Desktop>enex2paperless.exe -v Title.enex
[22:20:57.131] [ DEBUG:] configuration: {http://xxxxxx:8000 sssss wwwww [pdf txt jpeg png webp gif tiff]} {}
[22:20:57.182] [ DEBUG:] starting importENEX {}
[22:20:57.182] [ DEBUG:] waiting for WaitGroup {}
[22:20:57.182] [ DEBUG:] waiting for FailedNoteCatcher {}
[22:20:57.182] [  INFO:] ENEX processing done {"numberOfNotes":0,"totalUploads":0}
[22:20:57.183] [  INFO:] all notes processed successfully {}
```

Here the exported enex inside a zip, maybe you can reproduce it:

[Title.zip](https://github.com/kevinzehnder/enex2paperless/files/15120337/Title.zip)

Tomorrow I will try the same with the legacy windows Evernote app

**Comment by gunters63** [comment]
Oh, it was late yesterday :). I didn't see that the log said totalUploads 0. I will investigate later today.

Hmm strange, when I import the posted Enex file here again in Evernote, it works. If you open the enex, you can see the content and the tag,

**Comment by kevinzehnder** [comment]
I'll try to re-create it as soon as possible. Pretty busy at the moment.

**Comment by kevinzehnder** [comment]
Hey there. So this tool only imports note attachements from Evernote. It doesn't import anything from the notes itself. So in this case, nothing gets imported, because there's no file attached to the note. In these cases, the whole note gets ignored, which also means that any tags on that note won't get created.

**Comment by gunters63** [comment]
Yeah, I noticed that too. But I imported a lot of Evernote notes with attached documents also (most of them PDF).
While the notes were imported correctly by enex2paperless, the tags were missing.

I will prepare another enex test file with a single note with a tag and an attached PDF in Evernote and post it here.

**Comment by gunters63** [comment]
Here it is:

[test.zip](https://github.com/kevinzehnder/enex2paperless/files/15165351/test.zip)

**Comment by gunters63** [comment]
![image](https://github.com/kevinzehnder/enex2paperless/assets/90346/8996bc53-353e-404b-9bf0-040b9661e5ea)

This is the log when I import the file

**Comment by kevinzehnder** [comment]
I had no problems with that one: 

```
[15:57:23.518] [ DEBUG:] configuration: {http://paperboy.lan:8000 user pass [pdf txt jpeg png webp gif tiff]} {}
[15:57:23.518] [ DEBUG:] starting importENEX {}
[15:57:23.518] [ DEBUG:] waiting for WaitGroup {}
[15:57:23.518] [ DEBUG:] starting UploadFromNoteChannel {}
[15:57:23.518] [ DEBUG:] starting FailedNoteCatcher {}
[15:57:23.520] [ DEBUG:] opening file: assets/test.enex {}
[15:57:23.520] [ DEBUG:] decoding XML {}
[15:57:23.520] [ DEBUG:] closing noteChannel {}
[15:57:23.521] [  INFO:] processing file {"file":"test.pdf"}
[15:57:24.091] [ DEBUG:] tag not found {}
[15:57:24.091] [ DEBUG:] creating tag {"tag":"tag1"}
[15:57:24.628] [ DEBUG:] sending request {}
[15:57:25.218] [ DEBUG:] waiting for FailedNoteCatcher {}
[15:57:25.218] [  INFO:] ENEX processing done {"numberOfNotes":1,"totalUploads":1}
[15:57:25.218] [  INFO:] all notes processed successfully {}
```

**Comment by gunters63** [comment]
Oh, that one got the tag imported now. 

Ok back to square one. There is a difference between my real notebooks which i imported (with tags missing) and the test one here. I try to provide something which reproduces the problem better.

**Comment by gunters63** [comment]
Yeah, embarrassing. Tags are importing fine. I had a little oversight in my test setup ;)

Sorry for bothering, closing issue.

**Comment by kevinzehnder** [comment]
No problem :)
