### ISSUE TITLE
Enex with multiple images gets imported as separate documents

### ISSUE THREAD

**Issue by chakatodd** [kevinzehnder/enex2paperless#7]
A note in Enex can have multiple resources. These resource are images in my notes. When they get imported, each image becomes a separate document with duplicated document names. It would be great if the images were in one document. Thanks.

**Comment by kevinzehnder** [comment]
Is it possible to have a Paperless document that consists of multiple image files? I'll look into that.

**Comment by kevinzehnder** [comment]
As far as I can tell, this is not something that's possible with Paperless.  I can't create a Paperless document that consists of multiple files, so I think I can't handle your request. 

It would be possible to collect a note with multiple images into a single PDF file and then ingest that. However, doing that automatically is outside of the scope of this tool I think.
